### ISSUE TITLE
Moodle 3.9 issues with Modchooser

### ISSUE THREAD

**Issue by dbnschools** [willianmano/moodle-format_timeline#1]
I am sure you are aware of it but in Moodle 3.9 the Timeline format throws an error due to the new Activity Chooser.  In Moodle 3.8 it works amazing!  I love it.

get_module_metadata is deprecated. Please use \core_course\local\service\content_item_service instead.
line 3325 of /lib/deprecatedlib.php: call to debugging()
line 290 of /course/format/timeline/classes/output/timeline.php: call to get_module_metadata()
line 86 of /course/format/timeline/classes/output/timeline.php: call to format_timeline\output\timeline->get_activitychooser()
line 238 of /lib/outputrenderers.php: call to format_timeline\output\timeline->export_for_template()
line 481 of /lib/outputrenderers.php: call to renderer_base->render()
line 53 of /course/format/timeline/format.php: call to plugin_renderer_base->render()
line 290 of /course/view.php: call to require()
Exception - Class 'core_course\output\modchooser' not found

More information about this error

×Debug info:
Error code: generalexceptionmessage
×Stack trace:
line 415 of /course/format/timeline/classes/output/timeline.php: Error thrown
line 368 of /course/format/timeline/classes/output/timeline.php: call to format_timeline\output\timeline->course_modchooser()
line 86 of /course/format/timeline/classes/output/timeline.php: call to format_timeline\output\timeline->get_activitychooser()
line 238 of /lib/outputrenderers.php: call to format_timeline\output\timeline->export_for_template()
line 481 of /lib/outputrenderers.php: call to renderer_base->render()
line 53 of /course/format/timeline/format.php: call to plugin_renderer_base->render()
line 290 of /course/view.php: call to require()

**Comment by willianmano** [comment]
@dbnschools solved at mater branch
