### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by rschrenk** [willianmano/moodle-format_timeline#11]
Hello,

after doing a fresh install and activating it in an empty course, I only get errors

![format_timeline](https://user-images.githubusercontent.com/8080807/110507863-ba450280-8100-11eb-8208-066e282bc5ac.png)

**Comment by willianmano** [comment]
@rschrenk use the right version for your moodle. The repo has branches for moodle 3.8, 3.9 and 3.10.
