### ISSUE TITLE
Top Section is viewable as a student

### ISSUE THREAD

**Issue by demontech** [willianmano/moodle-format_timeline#2]
Hi Willian,

Excellent format idea !

The top section on your last commit cea3225 is viewable by the student

![image](https://user-images.githubusercontent.com/8148238/90718895-e7ff5280-e267-11ea-82ca-6056a4fbff5e.png)

Thank you for this great course format!

**Comment by mudrd8mz** [comment]
+1 I just noticed the same. This is a serious usability bug.
