### ISSUE TITLE
Non-English UI string shown with English set as the current language

### ISSUE THREAD

**Issue by mudrd8mz** [willianmano/moodle-format_timeline#3]
![image](https://user-images.githubusercontent.com/85831/92872848-bdd42700-f406-11ea-8b76-761c45fffd2f.png)

**Comment by mudrd8mz** [comment]
It is hard-coded in timeline/templates/timeline_post_item.mustache - needs to be turned into `{{#str}}`

**Comment by mudrd8mz** [comment]
Oh, there seem to be more cases like that

![image](https://user-images.githubusercontent.com/85831/92874024-f0325400-f407-11ea-98f2-61097514ba33.png)

**Comment by dbnschools** [comment]
Is it possible that these updates were only done to the Moodle 3.8 branch and not the 3.9 branch?  We are testing on Moodle 3.9 and still see the language strings.
