### ISSUE TITLE
A working version for 3.10?

### ISSUE THREAD

**Issue by marycooch** [willianmano/moodle-format_timeline#8]
Hello. I really like the idea of the Timeline and would like to blog about it on moodle.com but when I installed it on a Moodle 3.10 site I got the error message as below and I assume this means it does not support versions after 3.8. When will you be able to update the plugin for 3.10? Thanks!
![timelinebug](https://user-images.githubusercontent.com/2129086/108607713-f7e42480-73b9-11eb-9705-94d7e94045d6.png)

**Comment by willianmano** [comment]
@marycooch fixed.
